#LABEL INSTRUCTION
FROM alpine:3

LABEL author="Resandy Prisadana"
LABEL NIM="2205551050" Kelas="Manajemen Jaringan Dan Server (E)" 
LABEL DosenPengampu="Anak Agung Ketut Agung Cahyawan Wiranatha, ST, MT"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"